### ISSUE TITLE
Reasons for being >=3.9?

### ISSUE THREAD

**Issue by melMass** [3dninjas/pdistx#38]
Hey Ninjas,

Thanks a lot for this tools.
I was wondering the reason for the 3.9+ requirement?

I need to use it with 3.7.7 😢 

Thanks

**Comment by coreprocess** [comment]
@melMass it is only necessary to run the tools. It can process code for older python versions. It is because of `ast.unparse` (https://github.com/3dninjas/pdistx/blob/main/pdistx/utils/source.py#L14, https://docs.python.org/3/library/ast.html#ast.unparse).

It is actually possible to install multiple python versions in parallel. Or you could run it via a docker container if you want to abstract that away.

**Comment by melMass** [comment]
Perfect thanks!
I'm testing the Packer in a quite large code base but have a few errors, I'm going read the code but I was wondering if there is a guide or doc on supported features/best practices.

**Comment by coreprocess** [comment]
@melMass Theoretically, all Python modules without binary code (not supported) and without resource/data files (works only in some cases) should work. However, we have only tested the tool with a limited set of PyPi modules so far. Please feel free to open new issues regarding specific problems, accompanied by reproducible test cases.
